#!/usr/bin/env node
/**
 * apply-seo.js
 *
 * Writes title / description / canonical / Open Graph / Twitter / JSON-LD
 * into every page listed in seo.config.json.
 *
 * Idempotent: every managed tag lives inside a marked block. Running this
 * script twice produces the same file, and any stray duplicate of a managed
 * tag elsewhere in <head> is removed.
 *
 * Node standard library only. No dependencies.
 *
 *   node scripts/apply-seo.js
 *   node scripts/apply-seo.js --check   (report only, writes nothing)
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CONFIG = path.join(ROOT, 'seo.config.json');

const BEGIN = '<!-- seo:begin (generated by scripts/apply-seo.js — edit seo.config.json instead) -->';
const END = '<!-- seo:end -->';

const checkOnly = process.argv.includes('--check');

function readConfig() {
  if (!fs.existsSync(CONFIG)) {
    console.error('seo.config.json not found at ' + CONFIG);
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(CONFIG, 'utf8'));
}

function esc(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function absolute(origin, rel) {
  if (!rel) return null;
  if (/^https?:\/\//i.test(rel)) return rel;
  return origin.replace(/\/+$/, '') + '/' + String(rel).replace(/^\/+/, '');
}

/** Remove a previously generated block, if present. */
function stripBlock(head) {
  const b = head.indexOf(BEGIN);
  const e = head.indexOf(END);
  if (b === -1 || e === -1 || e < b) return head;
  return head.slice(0, b) + head.slice(e + END.length);
}

/**
 * Remove managed tags that live outside our block, so we never end up
 * with two titles or two canonicals.
 */
function stripManagedTags(head) {
  let out = head;
  out = out.replace(/[ \t]*<title\b[^>]*>[\s\S]*?<\/title>\s*/gi, '');
  out = out.replace(/[ \t]*<meta\b[^>]*\bname=["']description["'][^>]*>\s*/gi, '');
  out = out.replace(/[ \t]*<link\b[^>]*\brel=["']canonical["'][^>]*>\s*/gi, '');
  out = out.replace(/[ \t]*<meta\b[^>]*\bproperty=["']og:[^"']*["'][^>]*>\s*/gi, '');
  out = out.replace(/[ \t]*<meta\b[^>]*\bname=["']twitter:[^"']*["'][^>]*>\s*/gi, '');
  // Only strip Organization JSON-LD; leave any other structured data alone.
  out = out.replace(
    /[ \t]*<script\b[^>]*type=["']application\/ld\+json["'][^>]*>\s*\{[\s\S]*?"@type"\s*:\s*"Organization"[\s\S]*?<\/script>\s*/gi,
    ''
  );
  return out;
}

function buildBlock(cfg, page) {
  const origin = cfg.site.origin.replace(/\/+$/, '');
  const url = origin + (page.path === '/' ? '/' : page.path);
  const img = page.ogImage ? absolute(origin, page.ogImage) : null;
  const L = [];

  L.push('  ' + BEGIN);
  L.push('  <title>' + esc(page.title) + '</title>');
  L.push('  <meta name="description" content="' + esc(page.description) + '">');
  L.push('  <link rel="canonical" href="' + esc(url) + '">');
  L.push('  <meta property="og:type" content="' + esc(page.ogType || 'website') + '">');
  L.push('  <meta property="og:site_name" content="' + esc(cfg.site.siteName) + '">');
  L.push('  <meta property="og:locale" content="' + esc(cfg.site.locale || 'en_US') + '">');
  L.push('  <meta property="og:title" content="' + esc(page.title) + '">');
  L.push('  <meta property="og:description" content="' + esc(page.description) + '">');
  L.push('  <meta property="og:url" content="' + esc(url) + '">');
  if (img) {
    L.push('  <meta property="og:image" content="' + esc(img) + '">');
    L.push('  <meta property="og:image:width" content="1200">');
    L.push('  <meta property="og:image:height" content="630">');
  }
  L.push('  <meta name="twitter:card" content="' + esc(img ? cfg.site.twitterCard : 'summary') + '">');
  L.push('  <meta name="twitter:title" content="' + esc(page.title) + '">');
  L.push('  <meta name="twitter:description" content="' + esc(page.description) + '">');
  if (img) L.push('  <meta name="twitter:image" content="' + esc(img) + '">');

  // Organization JSON-LD on the homepage only.
  if (page.path === '/' && cfg.organization) {
    const o = cfg.organization;
    const node = {
      '@context': 'https://schema.org',
      '@type': 'Organization',
      name: o.name,
      url: origin + '/',
      logo: absolute(origin, cfg.site.logo)
    };
    if (o.email) {
      node.contactPoint = [{
        '@type': 'ContactPoint',
        contactType: 'sales',
        email: o.email
      }];
    }
    if (o.address) {
      node.address = Object.assign({ '@type': 'PostalAddress' }, o.address);
    }
    L.push('  <script type="application/ld+json">');
    L.push(JSON.stringify(node, null, 2).split('\n').map(function (l) { return '  ' + l; }).join('\n'));
    L.push('  </script>');
  }

  L.push('  ' + END);
  return L.join('\n');
}

function processPage(cfg, page) {
  const file = path.join(ROOT, page.file);
  if (!fs.existsSync(file)) return { file: page.file, status: 'missing' };

  const original = fs.readFileSync(file, 'utf8');
  const m = original.match(/<head\b[^>]*>([\s\S]*?)<\/head>/i);
  if (!m) return { file: page.file, status: 'no-head' };

  const headOpenEnd = original.indexOf(m[0]) + m[0].indexOf(m[1]);
  const headInner = m[1];

  let cleaned = stripManagedTags(stripBlock(headInner));
  cleaned = cleaned.replace(/\n{3,}/g, '\n\n').replace(/\s*$/, '\n');

  const block = buildBlock(cfg, page);
  const newInner = cleaned + block + '\n';

  const updated =
    original.slice(0, headOpenEnd) + newInner + original.slice(headOpenEnd + headInner.length);

  if (updated === original) return { file: page.file, status: 'unchanged' };
  if (!checkOnly) fs.writeFileSync(file, updated, 'utf8');
  return { file: page.file, status: checkOnly ? 'would-change' : 'updated' };
}

/** Tag orphan / superseded pages with noindex so they are not indexed. */
function processNoindex(cfg, fileName) {
  const file = path.join(ROOT, fileName);
  if (!fs.existsSync(file)) return { file: fileName, status: 'missing' };
  const original = fs.readFileSync(file, 'utf8');
  const m = original.match(/<head\b[^>]*>([\s\S]*?)<\/head>/i);
  if (!m) return { file: fileName, status: 'no-head' };

  const headOpenEnd = original.indexOf(m[0]) + m[0].indexOf(m[1]);
  const headInner = m[1];

  let cleaned = stripBlock(headInner)
    .replace(/[ \t]*<meta\b[^>]*\bname=["']robots["'][^>]*>\s*/gi, '')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/\s*$/, '\n');

  const block =
    '  ' + BEGIN + '\n' +
    '  <meta name="robots" content="noindex, follow">\n' +
    '  ' + END;

  const updated =
    original.slice(0, headOpenEnd) + cleaned + block + '\n' +
    original.slice(headOpenEnd + headInner.length);

  if (updated === original) return { file: fileName, status: 'unchanged' };
  if (!checkOnly) fs.writeFileSync(file, updated, 'utf8');
  return { file: fileName, status: checkOnly ? 'would-change' : 'noindexed' };
}

/** Tag orphan / superseded pages with noindex so they are not indexed. */
function processNoindex(cfg, fileName) {
  const file = path.join(ROOT, fileName);
  if (!fs.existsSync(file)) return { file: fileName, status: 'missing' };
  const original = fs.readFileSync(file, 'utf8');
  const m = original.match(/<head\b[^>]*>([\s\S]*?)<\/head>/i);
  if (!m) return { file: fileName, status: 'no-head' };

  const headOpenEnd = original.indexOf(m[0]) + m[0].indexOf(m[1]);
  const headInner = m[1];

  let cleaned = stripBlock(headInner)
    .replace(/[ \t]*<meta\b[^>]*\bname=["']robots["'][^>]*>\s*/gi, '')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/\s*$/, '\n');

  const block =
    '  ' + BEGIN + '\n' +
    '  <meta name="robots" content="noindex, follow">\n' +
    '  ' + END;

  const updated =
    original.slice(0, headOpenEnd) + cleaned + block + '\n' +
    original.slice(headOpenEnd + headInner.length);

  if (updated === original) return { file: fileName, status: 'unchanged' };
  if (!checkOnly) fs.writeFileSync(file, updated, 'utf8');
  return { file: fileName, status: checkOnly ? 'would-change' : 'noindexed' };
}

function main() {
  const cfg = readConfig();
  console.log('apply-seo' + (checkOnly ? ' (check only)' : '') + ' — origin ' + cfg.site.origin);
  console.log('-'.repeat(60));
  let changed = 0, missing = 0;
  cfg.pages.forEach(function (p) {
    const r = processPage(cfg, p);
    if (r.status === 'updated' || r.status === 'would-change') changed++;
    if (r.status === 'missing' || r.status === 'no-head') missing++;
    console.log('  ' + r.status.padEnd(13) + r.file);
  });
  (cfg.noindexPages || []).forEach(function (f) {
    const r = processNoindex(cfg, f);
    if (r.status === 'noindexed' || r.status === 'would-change') changed++;
    console.log('  ' + r.status.padEnd(13) + f);
  });
  console.log('-'.repeat(60));
  console.log(cfg.pages.length + ' pages, ' + changed + ' changed, ' + missing + ' problems');
  if (missing > 0) process.exitCode = 1;
}

main();
